version: "3.8"

services:
  db:
    image: postgres:latest
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: collegesystem
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - app-network


  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

  api:
    build: .
    ports:
      - "3000:3000"
    restart: on-failure
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PWD: 1234
      DB_NAME: collegesystem
      JWT_SECRET: yourseceret
      JWT_REFRESH_SECRET: yourseceret
      REDIS_URL: redis://redis:6379
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - app-network

networks:
  app-network:
