openapi: 3.0.0
info:
  title: Profile API
  description: API for managing user profiles.
  version: 1.0.0
paths:
  /api/v1/profile:
    get:
      summary: Get User Profile
      description: Retrieves the profile of the authenticated user.
      tags:
        - Profile
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Profile found successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Profile found successfully"
                  profile:
                    type: object
                    properties:
                      id:
                        type: string
                        example: "uuid"
                      firstName:
                        type: string
                        example: "John"
                      lastName:
                        type: string
                        example: "Doe"
                      dob:
                        type: string
                        format: date
                        example: "1990-01-01"
                      contactNumber:
                        type: string
                        example: "+1234567890"
                      address:
                        type: string
                        example: "123 Main St, Anytown, USA"
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Unauthorized"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Internal server error"

  /api/v1/profile/create:
    post:
      summary: Create User Profile
      description: Creates a profile for the authenticated user.
      tags:
        - Profile
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                  example: "John"
                lastName:
                  type: string
                  example: "Doe"
                dob:
                  type: string
                  format: date
                  example: "1990-01-01"
                contactNumber:
                  type: string
                  example: "+1234567890"
                address:
                  type: string
                  example: "123 Main St, Anytown, USA"
      responses:
        '201':
          description: Profile created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Profile created successfully"
                  profile:
                    type: object
                    properties:
                      id:
                        type: string
                        example: "uuid"
                      firstName:
                        type: string
                        example: "John"
                      lastName:
                        type: string
                        example: "Doe"
                      dob:
                        type: string
                        format: date
                        example: "1990-01-01"
                      contactNumber:
                        type: string
                        example: "+1234567890"
                      address:
                        type: string
                        example: "123 Main St, Anytown, USA"
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Unauthorized"
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Missing required profile data"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Internal server error"

  /api/v1/profile/update:
    put:
      summary: Update User Profile
      description: Updates the profile of the authenticated user.
      tags:
        - Profile
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                  example: "John"
                lastName:
                  type: string
                  example: "Doe"
                dob:
                  type: string
                  format: date
                  example: "1990-01-01"
                contactNumber:
                  type: string
                  example: "+1234567890"
                address:
                  type: string
                  example: "123 Main St, Anytown, USA"
      responses:
        '200':
          description: Profile updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Profile updated successfully"
                  profile:
                    type: object
                    properties:
                      id:
                        type: string
                        example: "uuid"
                      firstName:
                        type: string
                        example: "John"
                      lastName:
                        type: string
                        example: "Doe"
                      dob:
                        type: string
                        format: date
                        example: "1990-01-01"
                      contactNumber:
                        type: string
                        example: "+1234567890"
                      address:
                        type: string
                        example: "123 Main St, Anytown, USA"
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Unauthorized"
        '404':
          description: Profile not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Profile not found"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Internal server error"

  /api/v1/profile/delete:
    delete:
      summary: Delete User Profile
      description: Deletes the profile of the authenticated user.
      tags:
        - Profile
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Profile deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Profile deleted successfully"
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Unauthorized"
        '404':
          description: Profile not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Profile not found"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Internal server error"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Profile:
      type: object
      properties:
        id:
          type: string
          example: "uuid"
        firstName:
          type: string
          example: "John"
        lastName:
          type: string
          example: "Doe"
        dob:
          type: string
          format: date
          example: "1990-01-01"
        contactNumber:
          type: string
          example: "+1234567890"
        address:
          type: string
          example: "123 Main St, Anytown, USA"
    Error:
      type: object
      properties:
        message:
          type: string
